-- MySQL Script generated by MySQL Workbench
-- Fri May  9 14:44:27 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_sales
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_sales
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_sales` DEFAULT CHARACTER SET utf8 ;
USE `db_sales` ;

-- -----------------------------------------------------
-- Table `db_sales`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sales`.`customers` (
  `customer_id` INT NOT NULL AUTO_INCREMENT,
  `last_name` VARCHAR(45) NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `city` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sales`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sales`.`items` (
  `item_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `cost_price` DECIMAL(7,2) NOT NULL,
  `sell_price` DECIMAL(7,2) NULL,
  `supplier_name` VARCHAR(45) NOT NULL,
  `customers_customer_id` INT NOT NULL,
  PRIMARY KEY (`item_id`),
  INDEX `fk_items_customers_idx` (`customers_customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_items_customers`
    FOREIGN KEY (`customers_customer_id`)
    REFERENCES `db_sales`.`customers` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sales`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sales`.`orders` (
  `order_id` INT NOT NULL AUTO_INCREMENT,
  `date_ordered` DATE NOT NULL,
  `date_delivered` DATE NOT NULL,
  `status` ENUM('pending', 'delivered') NOT NULL,
  `customer_id` INT NOT NULL,
  PRIMARY KEY (`order_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_sales`.`orderline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_sales`.`orderline` (
  `order_id` INT NOT NULL,
  `item_id` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`order_id`, `item_id`),
  INDEX `fk_orders_has_items_items1_idx` (`item_id` ASC) VISIBLE,
  INDEX `fk_orders_has_items_orders1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_orders_has_items_orders1`
    FOREIGN KEY (`order_id`)
    REFERENCES `db_sales`.`orders` (`order_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_has_items_items1`
    FOREIGN KEY (`item_id`)
    REFERENCES `db_sales`.`items` (`item_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
