-- MySQL Script generated by MySQL Workbench
-- Fri Jul 18 10:38:52 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sheeshcuit
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sheeshcuit
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sheeshcuit` DEFAULT CHARACTER SET utf8 ;
USE `sheeshcuit` ;

-- -----------------------------------------------------
-- Table `sheeshcuit`.`productCategories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`productCategories` (
  `categoryId` INT NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(50) NULL,
  PRIMARY KEY (`categoryId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`products` (
  `productId` INT NOT NULL AUTO_INCREMENT,
  `productName` VARCHAR(45) NOT NULL,
  `productPrice` DECIMAL NOT NULL,
  `productCategories_categoryId` INT NOT NULL,
  PRIMARY KEY (`productId`),
  INDEX `fk_products_productCategories1_idx` (`productCategories_categoryId` ASC),
  CONSTRAINT `fk_products_productCategories1`
    FOREIGN KEY (`productCategories_categoryId`)
    REFERENCES `sheeshcuit`.`productCategories` (`categoryId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`suppliers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`suppliers` (
  `supplierId` INT NOT NULL AUTO_INCREMENT,
  `supplierName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`supplierId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`inventory` (
  `inventoryId` INT NOT NULL AUTO_INCREMENT,
  `productStock` INT NULL,
  `productId` INT NOT NULL,
  `products_productId` INT NOT NULL,
  `suppliers_supplierId` INT NOT NULL,
  PRIMARY KEY (`inventoryId`, `products_productId`, `suppliers_supplierId`),
  INDEX `fk_inventory_products_idx` (`products_productId` ASC),
  INDEX `fk_inventory_suppliers1_idx` (`suppliers_supplierId` ASC),
  CONSTRAINT `fk_inventory_products`
    FOREIGN KEY (`products_productId`)
    REFERENCES `sheeshcuit`.`products` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_inventory_suppliers1`
    FOREIGN KEY (`suppliers_supplierId`)
    REFERENCES `sheeshcuit`.`suppliers` (`supplierId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`customers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`customers` (
  `customerId` INT NOT NULL AUTO_INCREMENT,
  `customerFname` VARCHAR(45) NOT NULL,
  `customerLname` VARCHAR(45) NOT NULL,
  `customerAddress` VARCHAR(45) NOT NULL,
  `customerPhone` INT NULL,
  PRIMARY KEY (`customerId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`cart` (
  `cartId` INT NOT NULL AUTO_INCREMENT,
  `products_productId` INT NOT NULL,
  `customers_customerId` INT NOT NULL,
  PRIMARY KEY (`cartId`, `products_productId`, `customers_customerId`),
  INDEX `fk_cart_products1_idx` (`products_productId` ASC),
  INDEX `fk_cart_customers1_idx` (`customers_customerId` ASC),
  CONSTRAINT `fk_cart_products1`
    FOREIGN KEY (`products_productId`)
    REFERENCES `sheeshcuit`.`products` (`productId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cart_customers1`
    FOREIGN KEY (`customers_customerId`)
    REFERENCES `sheeshcuit`.`customers` (`customerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`sales` (
  `salesId` INT NOT NULL AUTO_INCREMENT,
  `salesDate` DATE NOT NULL,
  PRIMARY KEY (`salesId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`orders` (
  `orderId` INT NOT NULL AUTO_INCREMENT,
  `orderDate` DATE NOT NULL,
  `orderStatus` VARCHAR(45) NOT NULL,
  `sales_salesId` INT NOT NULL,
  PRIMARY KEY (`orderId`, `sales_salesId`),
  INDEX `fk_orders_sales1_idx` (`sales_salesId` ASC),
  CONSTRAINT `fk_orders_sales1`
    FOREIGN KEY (`sales_salesId`)
    REFERENCES `sheeshcuit`.`sales` (`salesId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`orderItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`orderItems` (
  `orderItemsId` INT NOT NULL AUTO_INCREMENT,
  `productQty` INT NOT NULL,
  `orders_orderId` INT NOT NULL,
  `cart_cartId` INT NOT NULL,
  `cart_products_productId` INT NOT NULL,
  `cart_customers_customerId` INT NOT NULL,
  PRIMARY KEY (`orderItemsId`, `orders_orderId`, `cart_cartId`, `cart_products_productId`, `cart_customers_customerId`),
  INDEX `fk_orderItems_orders1_idx` (`orders_orderId` ASC),
  INDEX `fk_orderItems_cart1_idx` (`cart_cartId` ASC, `cart_products_productId` ASC, `cart_customers_customerId` ASC),
  CONSTRAINT `fk_orderItems_orders1`
    FOREIGN KEY (`orders_orderId`)
    REFERENCES `sheeshcuit`.`orders` (`orderId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderItems_cart1`
    FOREIGN KEY (`cart_cartId` , `cart_products_productId` , `cart_customers_customerId`)
    REFERENCES `sheeshcuit`.`cart` (`cartId` , `products_productId` , `customers_customerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`expenses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`expenses` (
  `expensesId` INT NOT NULL AUTO_INCREMENT,
  `expenseDate` DATE NOT NULL,
  PRIMARY KEY (`expensesId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sheeshcuit`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sheeshcuit`.`users` (
  `userId` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`userId`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;


